go:
  version: 1.25.5
repository:
  path: github.com/prometheus/alertmanager
build:
  binaries:
    - name: alertmanager
      path: ./cmd/alertmanager
    - name: amtool
      path: ./cmd/amtool
  tags:
    all:
      - netgo
  ldflags: |
    -w
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
