---
name: Build Alertmanager image
on:
  push:
    branches:
      - main
    paths:
      - 'alertmanager/**'
      - '!alertmanager/README.md'
      - '.github/workflows/build-alertmanager.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Build and push image to registry
        uses: ./.github/actions/build-image
        with:
          name: alertmanager
          version: 0.29.0
          description: Prometheus Alertmanager
          license: Apache-2.0
          token: ${{ secrets.GITHUB_TOKEN }}
