---
name: Build Ubuntu images
on:
  push:
    branches:
      - main
    paths:
      - 'ubuntu/**'
      - '!ubuntu/**/README.md'
      - '.github/workflows/build-ubuntu.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['25.10-init', '24.04-init']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Extract Ubuntu release version
        id: version
        shell: bash
        run: echo "release=${VERSION%-init}" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ matrix.version }}

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          name: ubuntu
          version: ${{ matrix.version }}
          description: Custom Ubuntu ${{ steps.version.outputs.release }} system container image
          build-context: ./ubuntu/${{ matrix.version }}
          token: ${{ secrets.GITHUB_TOKEN }}