---
name: Build coreos-toolbox image
on:
  push:
    branches:
      - main
    paths:
      - 'coreos-toolbox/**'
      - '!coreos-toolbox/README.md'
      - '.github/workflows/build-coreos-toolbox.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      matrix:
        version: ['42','43']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          name: coreos-toolbox
          version: ${{ matrix.version }}
          description: Custom Fedora ${{ matrix.version }} image including utilities and tools for debugging on Fedora CoreOS
          build-extra-labels: |
            com.github.containers.toolbox=true
          token: ${{ secrets.GITHUB_TOKEN }}